# Generated by Django 5.1 on 2024-08-23 20:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50, unique=True)),
                ('take_a_shower', models.BooleanField(default=False)),
                ('eat_breakfast', models.BooleanField(default=False)),
                ('go_to_school', models.BooleanField(default=False)),
                ('play_games', models.BooleanField(default=False)),
                ('go_to_bed_early', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
