# Generated by Django 5.1 on 2024-08-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='user_id',
            new_name='code',
        ),
    ]
